# Site Settings
lang: en
title: Tripal
tagline: An open-source toolkit for construction of genomic, genetic, breeding and biological databases.
description: >- # this means to ignore newlines until "baseurl:"
  Tripal is a toolkit for construction of online biological (genetics, genomics, breeding, etc), community database web portals. Use Tripal out-of-the box to create a basic genomics site (with no programming) or customize using Tripal's Application Programming Interface (API). Tripal is free and open-source (GNU General Public License version 2), allows for extensive customization and is backed by a helpful user community. A strength of Tripal is our community of developers. Customization and extension of Tripal can be created and shared with other sites as modules allowing you to create your own tools and visualizations or leverage those developed by groups around the world.

baseurl: ""
url: ""
permalink: pretty
github_username: tripal
#favicon: /path/to/favicon.png
#gh_sponsor: tripal
force_theme: light

theme: bulma-clean-theme

# Front matter Defaults.
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      show_sidebar: false

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname:

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true
